name: Lotto Auto Update

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '35 12 * * 6'

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 supabase
      - name: Run Update Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python update_lotto.py  # 명칭을 파일명과 일치시킴
